accounts/urls.py
from django.urls import path
from django.contrib.auth import views as admin_views
from django.contrib.auth.urls import urlpatterns
from django.views.generic import TemplateView


from .views import (
                    RegisterView,
                    ProfileDetailView,
                    ProfileUpdateView,
                    ProfileCreateView,
                    CustomResetPasswordConfirmView,
                    CheckCodeView,
                    )

urlpatterns = [
    # path('send-reset-code/', send_reset_code, name='send_reset_code'),
    path('check-code/', CheckCodeView.as_view(), name='check_code'),

    path('profile/', ProfileDetailView.as_view(), name='profile'),
    path('profile-create/', ProfileCreateView.as_view(), name='profile_create'),
    path('profile-update/<str:pk>/', ProfileUpdateView.as_view(), name='profile_update'),

    path('register/', RegisterView.as_view(), name='register'),
    path('login/', admin_views.LoginView.as_view(), name='login'),
    path('logout/', admin_views.LogoutView.as_view(), name='logout'),
    path('password-change/', admin_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change-done/', admin_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset-confirm/', CustomResetPasswordConfirmView, name='password_reset_confirm'),
    path('password-reset-done/', admin_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('exam/', include('exam.urls')),
    path('accounts/', include('accounts.urls')),
    path('takingtest/', include('takingtest.urls')),
    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
                    QuestionListView, 
                    QuizListView, 
                    QuizDetailView, 
                    QuizQuestionUpdateView, 
                    QuestionCreateView, 
                    QuestionUpdateView,
                    QuestionDetailView,
                    question_delete_view,
                    QuestionListView,
                    QuizCreateView,
                    QuizQuestionCreateView,
                    quiz_delete
                    )

urlpatterns = [
    path('test/', TemplateView.as_view(template_name="exam/test.html"), name="test"),
    path('test2/', TemplateView.as_view(template_name="exam/quiz/quiz_question_create.html"), name="test"),

    path('quiz-list/', QuizListView.as_view(), name="quiz_list"),
    path('quiz-create/', QuizCreateView.as_view(), name="quiz_create"),
    path('quiz-delete/', quiz_delete, name="quiz_delete"),
    path('quiz-detail/<str:pk>/', QuizDetailView.as_view(), name="quiz_detail"),
    path('quiz-question-create/<str:pk>/', QuizQuestionCreateView.as_view(), name="quiz_question_create"),
    path('quiz-question-update/<str:pk>/', QuizQuestionUpdateView.as_view(), name="quiz_question_update"),

    path('question-create/', QuestionCreateView.as_view(), name="question_create"),
    path('question-update/<str:pk>/', QuestionUpdateView.as_view(), name="question_update"),
    path('question-detail/<str:pk>/', QuestionDetailView.as_view(), name="question_detail"),
    path('question-list/', QuestionListView.as_view(), name="question_list"),

    path('question-delete/<str:pk>/', question_delete_view, name="question_delete"),
]

accounts/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator

from extensions.utils import jalali_convertor

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
#     CHOICES = (
#         ('light', 'light'),
#         ('dark', 'dark')
#     )
#     theme = models.CharField(choices=CHOICES, max_length=32, default='light')


class Profile(models.Model):
    CHOICES = (
        ('1', 'پزشکی'),
        ('2', 'پرستاری'),
    )
    GENDER_CHOICES = (
        ('1', 'آقا'),
        ('2', 'خانم'),
    )
    phone_number_validator=[RegexValidator(r'^[0-9]*$', 'Only numerical values are allowed.')]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=True)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, related_name='profile')
    phone_number = models.CharField(max_length=11, unique=True, validators=phone_number_validator)
    phone_number_confirm = models.BooleanField(default=False)
    term = models.PositiveIntegerField(default=1)
    discipline = models.CharField(choices=CHOICES, max_length=7, default=1)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=7)


    def j_datetime_joined(self):
        return jalali_convertor(self.last_login)
    

class VerificationCode(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="verification_code")
    code = models.CharField(max_length=255)
    datetime_created = models.DateTimeField(auto_now_add=True)


class IpAdress(models.Model):
    ip = models.CharField(max_length=255)
    datetime_created = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Profile
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2')


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('term', 'phone_number', 'gender')


class CustomPasswordResetForm(forms.Form):

    new_password1 = forms.PasswordInput()
    new_password2 = forms.PasswordInput()

accounts/views.py
from django.http import JsonResponse
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DetailView, TemplateView, UpdateView, ListView
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout
from django.urls import reverse_lazy, reverse
from django.contrib.auth import views as admin_views
from django.contrib.auth.views import PasswordResetConfirmView
from django.db.models import Avg, Sum, Count
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import views as admin_views
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password
from django.conf import settings
from django.utils import timezone


from .models import Profile, VerificationCode
from .forms import RegisterForm, CustomPasswordResetForm
from exam.models import Question
from takingtest.models import QuizResult,QuizHistory
from .mixins import DoNotHaveProfileMixin, CheckHavingProfileMixin, SmsSendLimitByIpMixin
# from .models import Profile
from .send_code import send_code

class RegisterView(CreateView):
    model = get_user_model()
    template_name = "registration/register.html"
    form_class = RegisterForm
    # success_url = reverse_lazy('profile_create')

    def get_success_url(self):
        messages.success(
            self.request,
            "<strong>خوش آمدید !</strong>  اطلاعات شما با موفقیت ثبت شد. برای دسترسی به صفخات سامانه لظفا پروفایل خود را تکمیل کنید."
        )
        login(self.request, self.object)
        return reverse('profile_create')
        
    # def post(self, request, *args, **kwargs):
    #     register_form = RegisterForm(request.POST)
    #     register_form.initial['password2'] = request.POST.get('password1')
    #     register_form.save()
        # mutable_post = request.POST.copy()  
        # request.POST['password2'] = request.POST.get('password1')
        # request.POST = mutable_post
        # return super().post(request, *args, **kwargs)

    


class CustomPasswordChangeView(admin_views.PasswordChangeView):
    success_url = reverse_lazy('password_change_don')


class ProfileDetailView(CheckHavingProfileMixin, TemplateView):
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        user = self.request.user

        context = super().get_context_data(**kwargs)

        user_score_sum = QuizResult.objects.filter(user=user).aggregate(score_avg=Sum("score"))['score_avg']
        user_question_answered_count = QuizHistory.objects.filter(user=user).count()
        
        try:
            user_score_avg = round(user_score_sum / user_question_answered_count * 100)
        except:
            user_score_avg = 0
        user_quiz_count = QuizResult.objects.filter(user=user).count()

        
        term_user_score_sum = QuizResult.objects.filter(user=user, quiz__lesson__term=user.profile.term).aggregate(score_avg=Sum("score"))['score_avg']
        term_user_question_answered_count = QuizHistory.objects.filter(user=user, quiz__lesson__term=user.profile.term).count()
        try:
            term_user_score_avg = round(term_user_score_sum / term_user_question_answered_count * 100)
        except:
            term_user_score_avg = 0

        term_user_quiz_count = QuizResult.objects.filter(user=user, quiz__lesson__term=user.profile.term).count()
        
        context['user_score_avg'] =  user_score_avg
        context['term_user_score_avg'] =  term_user_score_avg
        
        context['user_quiz_count'] = user_quiz_count
        context['term_user_quiz_count'] = term_user_quiz_count
        return context





class ProfileUpdateView(CheckHavingProfileMixin, UpdateView):
    model = Profile
    template_name = "accounts/profile_update.html"
    fields = ('term', 'phone_number', 'gender')
    success_url = reverse_lazy('profile')


    def post(self, request, *args, **kwargs):
        posted_data = self.request.POST
        profile = Profile.objects.get(id=kwargs.get('pk'))

        try:
                
            profile.term = int(posted_data.get('term'))
            # profile.phone_number = posted_data.get('phone_number')
            profile.gender = posted_data.get('gender')
            profile.discipline = posted_data.get('discipline')
            profile.save()

            user = self.request.user
            user.first_name = posted_data.get('first_name')
            user.last_name = posted_data.get('last_name')
            user.email = posted_data.get('email')
            user.save()
        except:
            pass

        return super().post(request, *args, **kwargs)
    
    def form_invalid(self, form) :
        # create a message that say your form have a problem
        return super().form_invalid(form)
    

    

class ProfileCreateView(LoginRequiredMixin, DoNotHaveProfileMixin, CreateView):
    model = Profile
    template_name = "accounts/profile_create.html"
    fields = ('term', 'phone_number', 'gender')

    def get(self, request, *args, **kwargs):
        if request.GET.get('phone_number'):
            phone_number = request.GET.get('phone_number')
            verification_code = VerificationCode.objects.filter(user=request.user).order_by('-datetime_created')
           
            # check user can send only one sms per 2 minutes 
            if verification_code:
                time_diffrence = timezone.now() - verification_code[0].datetime_created
                if time_diffrence.total_seconds() < 1 :
                    messages.error(
                        request,
                        f"<strong>خطا !</strong> هر دو دقیقه یکبار می توانید درخواست ارسال کد داشته باشید."
                    )
                    return JsonResponse({'error': 'some error'}, status=500)
            verification_code = send_code(request, phone_number)

            print(verification_code)
        return super().get(request, *args, **kwargs)
    
    def get_success_url(self):
        messages.success(
            self.request,
            "<strong>خوش آمدید !</strong>  اطلاعات شما با موفقیت ثبت شد"
                    )
        return reverse('profile') 
    
    def post(self, request, *args, **kwargs):
        posted_data = request.POST
        # check the sented code
        phone_number = posted_data.get('phone_number')
        profile_exist = Profile.objects.filter(phone_number=phone_number)

        # error if phone_number is not unique
        if profile_exist:
            messages.error(
                    request,
                    f"<strong>خطا !</strong> شماره تلفن قبلا در سیستم ثبت شده است ."
                )
            return redirect('profile_create')
        
        # check correct code
        if not send_code(request, phone_number,posted_data.get('user_code')):
            messages.error(
                    request,
                    f"<strong>خطا !</strong> کد وارد شده غلط است ."
                )
            return redirect('profile_create')
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        posted_data = self.request.POST
        user = self.request.user
        form.instance.user = user
        form.instance.phone_number_confirm = True

        try:
            user.first_name = posted_data.get('first_name')
            user.last_name = posted_data.get('last_name')
            user.email = posted_data.get('first_name')
        except:
            self.form_invalid()
        return super().form_valid(form)
    

    def form_invalid(self, form) :
        # create a message that say your form have a problem
        posted_data = self.request.POST
        user_entries = {
        'first_name': posted_data.get('first_name'),
        'last_name': posted_data.get('last_name'),
        'email': posted_data.get('email'),
        'term': posted_data.get('term'),
        'phone_number': posted_data.get('phone_number'),
        'gender': posted_data.get('gender'),
        'error_message': 1,
        'fields':{
                'term': 0,
                'phone_number': 0,
                'gender': 0,

        }
                    }
        # handeling error by every fields
        # this code is not using
        if not form.cleaned_data.get('phone_number'):
            user_entries['fields']['phone_number'] = 'تلفن همراه <br>'
        if not form.cleaned_data.get('term'):
            user_entries['fields']['term'] = 'ترم <br>'
        if not form.cleaned_data.get('gender'):
            user_entries['fields']['gender'] = 'جنسیت <br>'
        


        self.request.session['user_entries'] = user_entries
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_entries'] = self.request.session.get('user_entries')

        
        #if ther is any error show it and then delete the error form sessions to don't show it again 
        if user_entries := self.request.session.get('user_entries'):
            if user_entries.get('error_message'):
                messages.error(
                self.request,
                f"<strong>اخطار !</strong> لطفا اطلاعات وارد شده را اصلاح کنید"
                )
                del self.request.session['user_entries']
            


        return context
    

class CustomLoginView(admin_views.LoginView):
    def form_valid(self, form: admin_views.AuthenticationForm):
        posted_data = self.request.POST
        form.instance.username = posted_data.get('username')
        form.instance.password = posted_data.get('password')
        return super().form_valid(form)
    




class CheckCodeView(SmsSendLimitByIpMixin, TemplateView):
    # form_class = CustomPasswordResetForm
    success_url = reverse_lazy('profile')

accounts/templates/accounts/profile_create.html
{% extends "_base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}
  <title>ساخت پروفایل </title>
{% endblock title %}

{% block head %}
    <!-- Custom Stylesheet -->
	<link href="{% static './vendor/jquery-nice-select/css/nice-select.css' %}" rel="stylesheet">
    <link href="{% static './css/style.css' %}" rel="stylesheet">
    <link href="{% static './css/custumize.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body farsi" dir="rtl">
            <div class="container-fluid">
                <div class="row page-titles">
                    <ol class="breadcrumb" dir="rtl" style="text-align: right;">
                        <li class="breadcrumb-item active"><a href="">حساب کاربری </a></li>
                        <li class=""><a href="">
                            <span class="text-primary">&nbsp; / </span>
                            ساخت پروفایل 
                        </a></li>
                        <!-- <li class="breadcrumb-item"><a href=""></a></li> -->
                        <!-- <li class=""><a href="">طراح سوالات : {{quiz.quiz_maker}}</a></li> -->
                    </ol>
                </div>
                <!-- row -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">برای استفاده از سامانه اطلاعات موارد زیر را تکمیل کنید : </h4>
                            </div>
                            <div class="card-body">
                                {% include "message.html" %}
                                <div class="form-validation">
                                    <form class="needs-validation" novalidate method="POST" >
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-xl-6">
                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="validationCustom01">نام :
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
														<input type="text" class="form-control" id="validationCustom01"  value="{{user_entries.first_name}}"  name="first_name" required>
														<div class="invalid-feedback">
															
														</div>
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="validationCustom01"> نام خانوادگی : 
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
														<input type="text" class="form-control" id="validationCustom01"  value="{{user_entries.last_name}}"  name="last_name" required>
														<div class="invalid-feedback">
															
														</div>
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="validationCustom02">ایمیل : <span
                                                            class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="email" class="form-control" id="validationCustom02"  value="{{user_entries.email}}" name="email" required>
														<div class="invalid-feedback">
															
														</div>
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="validationCustom05">جنسیت : 
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <select class="default-select wide form-control" id="validationCustom05" name="gender" style="text-align: right;border-color: red;"> <!-- text align = right -->
                                                            <option  data-display="{{user.profile.get_gender_display}}"
                                                            >انتخاب کنید</option>
                                                            <option value="1">آقا</option>
                                                            <option value="2">خانم</option>
                                                        </select>
                                                        <div class="invalid-feedback">
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-6">

                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="phone_number">تلفن همراه : 
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-4">
                                                        <input type="text" maxlength="11" minlength="11" class="form-control" id="phone_number" value="{{user.profile.phone_number}}" name="phone_number" required>
                                                        <!-- <input type="text" class="form-control" id="validationCustom08" value="6789 345 0912" name="phone_number" required> -->
														<div class="invalid-feedback">

														</div>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <button type="button" onclick="send_code()" class="btn btn-primary btn-block">ارسال کد تایید</button>
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="validationCustom08">کد تایید 
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-4">
                                                        <input type="text" maxlength="11" minlength="11" class="form-control" id="validationCustom08" value="" name="user_code" required>
                                                        <!-- <input type="text" class="form-control" id="validationCustom08" value="6789 345 0912" name="phone_number" required> -->
														<div class="invalid-feedback">

														</div>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <span class="btn btn-primary btn-block"> کد تایید</span>
                                                    </div>
                                                </div>

                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="id_term">ترم : <span
                                                        class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="number" class="form-control" id="id_term" value="{{user.profile.term}}" name="term" required>
														<div class="invalid-feedback">
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="mb-3 row">
                                                    <label class="col-lg-4 col-form-label" for="validationCustom05">رشته تحصیلی : 
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <select class="default-select wide form-control" id="validationCustom05" name="discipline" style="text-align: right;"> <!-- text align = right -->
                                                            <option  data-display="{{user.profile.get_discipline_display}}">انتخاب کنید</option>
                                                            <option value="1">پزشکی</option>
                                                            <option value="2">پرستاری</option>
                                                        </select>
                                                        <div class="invalid-feedback">
                                                            
                                                        </div>
                                                    </div>
                                                </div>
                                                
                                                <div class="mb-3 row">
                                                    <div class="col-lg-8 ms-auto">&nbsp;</div>
                                                    <div class="col-lg-4 ms-auto">&nbsp;</div>
                                                </div>
                                                <div class="mb-3 row" dir="ltr">
                                                    <div class="col-lg-6 ms-auto"></div>
                                                    <div class="col-lg-9 ms-auto">
                                                        <button type="submit" class="btn btn-secondary">ثبت اطلاعات</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->  
{% endblock content %}

{% block required_js %}
        <!-- Required vendors -->
        <script src="{% static './vendor/global/global.min.js' %}"></script>
        <script src="{% static './vendor/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>

        <script src="{% static './js/custom.js' %}"></script>
        <script src="{% static './js/dlabnav-init.js' %}"></script>
        <script src="{% static './js/demo.js' %}"></script>
        <script src="{% static './js/styleSwitcher.js' %}"></script>

        <script>
            var send_code = function() {
            const phone_number = document.getElementById('phone_number').value;
            fetch(`{% url 'profile_create' %}?phone_number=${phone_number}`)
                .then(response => response.json())
                .then(data => {
                    if (data.error) {
                        window.location.href ='{% url "profile_create" %}'
                    } 
                })
        
        }
        
        </script>
        


{% endblock required_js %}